version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "01:00"
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - "< 10.11.2"
    - ">= 10.11.1.a"
  - dependency-name: "@types/node"
    versions:
    - "< 10.12"
    - "> 10.11.2"
  - dependency-name: "@types/node"
    versions:
    - "> 11.9.0"
    - "< 11.10"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a"
    - "< 14"
  - dependency-name: "@wireapp/core"
    versions:
    - ">= 12.15.2.a"
    - "< 12.15.3"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 5.9.12"
    - ">= 5.9.11.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 5.9.13"
    - ">= 5.9.12.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 5.9.20"
    - ">= 5.9.19.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 5.9.21"
    - ">= 5.9.20.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 5.9.22"
    - ">= 5.9.21.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 5.9.25"
    - ">= 5.9.24.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 6.1.3"
    - ">= 6.1.2.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 6.2.2"
    - ">= 6.2.1.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 6.3.10"
    - ">= 6.3.9.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 6.3.11"
    - ">= 6.3.10.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 6.3.12"
    - ">= 6.3.11.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 6.3.2"
    - ">= 6.3.1.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 6.3.5"
    - ">= 6.3.4.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 6.3.9"
    - ">= 6.3.8.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 6.5.3"
    - ">= 6.5.2.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 6.5.4"
    - ">= 6.5.3.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 6.5.6"
    - ">= 6.5.5.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 6.5.7"
    - ">= 6.5.6.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 6.5.9"
    - ">= 6.5.8.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 7.2.7"
    - ">= 7.2.6.a"
  - dependency-name: "@wireapp/core"
    versions:
    - "< 7.2.8"
    - ">= 7.2.7.a"
  - dependency-name: "@wireapp/lru-cache"
    versions:
    - "< 2.1.53"
    - ">= 2.1.52.a"
  - dependency-name: "@wireapp/lru-cache"
    versions:
    - "< 3.0.12"
    - ">= 3.0.11.a"
  - dependency-name: "@wireapp/lru-cache"
    versions:
    - "< 3.0.13"
    - ">= 3.0.12.a"
  - dependency-name: "@wireapp/lru-cache"
    versions:
    - "< 3.0.2"
    - ">= 3.0.1.a"
